### ISSUE TITLE
Storybook integration error

### ISSUE THREAD

**Issue by rynzlery** [JimmyBeldone/gatsby-plugin-breakpoints#116]
Hi, first of all, thanks a lot for this plugin.
I am using storybook, and I got this error on storybook after setting up this plugin on a component : 
`useBreakpoint must be used within BreakpointProvider`

I tried using the `<BreakpointProvider />` tag with no success.

it's not blocking me because it's working perfectly on my gatsby project, but it's a little annoying :D

thanks

**Comment by JimmyBeldone** [comment]
Hi, 

I have never used storybook but hopefully we will fix your problem. 

But first could you please share your code or a reproductible example ?

**Comment by rynzlery** [comment]
Hi,
I actually have problems with my gatsby compiled & rendered CSS/JS ^^
I will add some news when it will work

**Comment by JimmyBeldone** [comment]
Alright, I let the issue open then. Keep me update.

In the meantime I looked into storybook :
`<BreakpointProvider />` which is suppose to wrap your app, must be included as storybook decorator with `addDecorator()`

I found this example with redux provider / storybook which is basically the same process.

https://github.com/fabianunger/gatsby-starter-redux-storybook/blob/master/.storybook/preview.js

**Comment by JimmyBeldone** [comment]
hey @rynzlery, did you managed to make it works with Storybook ? 
Can I close this issue ?

**Comment by rynzlery** [comment]
Hi, sorry for the late response. I didn't have enought time, so I didn't use storybook in the project for now. Thanks for your advice, you can close the issue

**Comment by JimmyBeldone** [comment]
No problem, you're welcome ;)
Feel free to re open it if you need to
