### ISSUE TITLE
Could not find a declaration file for module 'gatsby-plugin-breakpoints'. '/node_modules/gatsby-plugin-breakpoints/index.js' implicitly has an 'any' type.   

### ISSUE THREAD

**Issue by dkhole** [JimmyBeldone/gatsby-plugin-breakpoints#118]
Having problems with getting the breakpoint working. I went along with the example but breakpoint.md seems to always be false. VS Code is showing this  "Could not find a declaration file for module 'gatsby-plugin-breakpoints'. '/node_modules/gatsby-plugin-breakpoints/index.js' implicitly has an 'any' type.".

Tried npm install @types/gatsby-plugin-breakpoints but it didn't exist.

**Comment by JimmyBeldone** [comment]
Hi,

That looks like a Typescript error. `gatsby-plugin-breakpoints` is not written in Typescript so I have no declaration type file to export.

I have two quick fix solutions for you : 

- Either replace `import` with `require` like so :
```.ts
// import { useBreakpoint } from 'gatsby-plugin-breakpoints';
const { useBreakpoint } = require('gatsby-plugin-breakpoints');
```

- Or declare the module in a `.d.ts` file in the same folder you imported `gatsby-plugin-breakpoints` like so :
```.ts 
// pluginBreakpoint.d.ts
declare module 'gatsby-plugin-breakpoints'
```
Then when you import `gatsby-plugin-breakpoints` it will just be typed as `any`

**P.S** : It never hurts to start with a simple "Hi" ; )

**Comment by dkhole** [comment]
Hey Jimmy

The require didn't seem to work but delcaring the .d.ts file got rid of the error. Although i still couldn't get it going i don't think its the best solution for me. Anyway sorry for being a little crass in my first message but thanks for all the work youre doing :)
