### ISSUE TITLE
feat: export BreakpointContext

### ISSUE THREAD

**Issue by juanpprieto** [JimmyBeldone/gatsby-plugin-breakpoints#132]
Hey Jimmy thanks for the plugin. I have a tiny request.

I wonder if you could expose `BreakpointContext` in a next release.

I ran into a scenario (niche) while trying to put together a Gatsby starter theme for pure canvas-driven ThreeJS projects. i.e no DOM elements just Canvas as the layout root.

The main cocktail is gatsby, react-three-fiber and @react-three/drei.

The issue is that **react-three-fiber**'s Canvas (which will be the root element) doesn't allow ContextAPI consumption by react-three-fiber children unless its proxied via a "context bridge". **@react-three/drei** offers a solution via [useContextBridge()](https://github.com/pmndrs/drei#usecontextbridge). 

As you can see this hook proxies your contexts, so that they can be consumed by any child (.Shapes, Geometries  etc..
) within the Canvas tree by the usual React.useContext API.

I'd love to test your plugin for dealing with breakpoints within this Canvas ecosystem.

P.S - I've successfully proxied some local contexts I created but hit this roadblock with your plugin.

**Comment by JimmyBeldone** [comment]
Hey @juanpprieto,

It is done in 1.3.0, also updated the doc.

```javascript
import { BreakpointContext } from 'gatsby-plugin-breakpoints';
```

Hope it will fixes your issue ;)

**Comment by juanpprieto** [comment]
Amazing @JimmyBeldone. thanks for the quick turn around!

**Comment by JimmyBeldone** [comment]
My pleasure ;)

I let you close this if it works out after your tests

**Comment by juanpprieto** [comment]
All working great thanks!
