### ISSUE TITLE
Using the BreakpointContext Provider outside of pages in a component of wrapRootElement

### ISSUE THREAD

**Issue by MartinConde** [JimmyBeldone/gatsby-plugin-breakpoints#180]
Not too familiar with the whole context stuff so I'm probably just overlooking something, just can't figure it out.

Basically, I am trying to use your breakpoints in a component of my header. That header is in a layout component which is wrapped around the page using wrapRootElement (needs to be for some other stuff to work).

Now when I use the breakpoint hook in the header, I get the error that it needs to be in the BreakpointContext Provider. I imported the provider and added it to my component that wraps everything. The error is gone which makes me think it now has access to it. However, it is always empty so I can't target breakpoints.xs etc.

I was thinking I have to provide the correct value to the provider and tried poking around your code to find out which value to set. I tried the queryMatch and setQueryMatch but that's probably wrong.

Which would be the correct value? Or am I tackling this completely wrong?

Here is the element that wraps my pages:

```
import React, { useState } from "react"
import Layout from "../layout"
import { BreakpointContext } from "gatsby-plugin-breakpoints"

export const myContext = React.createContext()

const Provider = props => {
  const [logoPlayed, setLogoPlay] = useState(false)
  const [trans, setTrans] = useState()
  const [locale, setLocale] = useState()
  const [queryMatch, setQueryMatch] = useState({})

  return (
    <myContext.Provider
      value={{
        logoPlayed,
        changeTheme: () => setLogoPlay(true),
        trans,
        setTrans,
        locale,
        setLocale,
      }}
    >
      <BreakpointContext.Provider value={{ queryMatch, setQueryMatch }}>
        <Layout
          trans={trans ? trans : null}
          locale={locale ? locale.slice(0, 2).toLowerCase() : null}
        >
          {props.children}
        </Layout>
      </BreakpointContext.Provider>
    </myContext.Provider>
  )
}

export default ({ element }) => <Provider>{element}</Provider>
```

Any pointers would be much appreciated :)

**Comment by JimmyBeldone** [comment]
Hi !

Sorry for the late answer !
I don't have any time to work on my open source projects for now.

Did you figure it out ?

**Comment by MartinConde** [comment]
@JimmyBeldone 

No worries :) I haven't actually. I had to restructure some stuff for other reasons anyway and in that process, this issue resolved itself. If you ever do find the time though, it would be cool if you could add a quick example to the readme.
