### ISSUE TITLE
useBreakpoint returns empty object

### ISSUE THREAD

**Issue by beardwin** [JimmyBeldone/gatsby-plugin-breakpoints#191]
Hello!

I'm brand new to gatsby (v3) and am trying to leverage this plugin. I've installed it with defaults. No matter what I do `useBreakpoint()` returns an empty object. 

I've tried manually wrapping my Layout with a `BreakpointProvider` and providing my own queries, but still nothing.

Is there something missing from the README?

**Comment by beardwin** [comment]
ha! oh man.... nevermind. This was a classic case of PEBKAC. I was staring at the gatsby console, not the console in Chrome's developer tools. 

![han](https://user-images.githubusercontent.com/42842566/121267441-2fec7600-c88a-11eb-877e-5a723fd2b14c.gif)

**Comment by JimmyBeldone** [comment]
Yeah I know that feeling ^^
