### ISSUE TITLE
Does this work for latest Gatsby/React version?

### ISSUE THREAD

**Issue by justinledelson** [JimmyBeldone/gatsby-plugin-breakpoints#250]
Got this error when trying to install to a new project:

`# npm resolution error report

2022-07-06T17:03:32.620Z

While resolving: my-site@1.0.0
Found: react@18.2.0
node_modules/react
  react@"^18.1.0" from the root project
  peer react@"^16.9.0 || ^17.0.0 || ^18.0.0" from gatsby@4.18.0
  node_modules/gatsby
    gatsby@"^4.18.0" from the root project
    peer gatsby@"^2.0.0 || ^3.0.0 || ^4.0.0" from gatsby-plugin-breakpoints@1.3.7
    node_modules/gatsby-plugin-breakpoints
      gatsby-plugin-breakpoints@"*" from the root project
  peer react@"^18.2.0" from react-dom@18.2.0
  node_modules/react-dom
    react-dom@"^18.1.0" from the root project
    peer react-dom@"^16.9.0 || ^17.0.0 || ^18.0.0" from gatsby@4.18.0
    node_modules/gatsby
      gatsby@"^4.18.0" from the root project
      peer gatsby@"^2.0.0 || ^3.0.0 || ^4.0.0" from gatsby-plugin-breakpoints@1.3.7
      node_modules/gatsby-plugin-breakpoints
        gatsby-plugin-breakpoints@"*" from the root project

Could not resolve dependency:
peer react@"^16.13.1 || ^17.0.0" from gatsby-plugin-breakpoints@1.3.7
node_modules/gatsby-plugin-breakpoints
  gatsby-plugin-breakpoints@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by gerardolmos** [comment]
I have the same problem. Seems not to be compatible with R. v.18.1

**Comment by leomitimiti** [comment]
Support for React v18?

https://github.com/JimmyBeldone/gatsby-plugin-breakpoints/pull/240

**Comment by enmalidia** [comment]
I upgraded Gatsby to the v5.0.1 and now I'm getting: "Plugin gatsby-plugin-breakpoints is not compatible with your gatsby version 5.0.1 - It requires gatsby@^2.0.0 || ^3.0.0 || ^4.0.0"
The plugin is not compatible with the latest version?

**Comment by mariaadobos** [comment]
Have the same problem here

**Comment by therealtgd** [comment]
Same problem here

**Comment by ykollega** [comment]
Same

**Comment by JimmyBeldone** [comment]
Hi guys ! 
Really sorry for the delay ! Just published a new version
