### ISSUE TITLE
Package installed via npm has old peerDependencies

### ISSUE THREAD

**Issue by hitfactory** [JimmyBeldone/gatsby-plugin-breakpoints#264]
Even though, I have "gatsby-plugin-breakpoints": "^1.3.9", in my package.json file, after npm install, the package.json from gatsby-plugin-breakpoints looks like below. 

You can see that it still says  "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0" instead of "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0". 

This is preventing me from upgrading to Gatsby5.

```
{
  "name": "gatsby-plugin-breakpoints",
  "version": "1.3.9",
  "description": "Gatsby plugin providing breakpoints using React Hooks",
  "keywords": [
    "gatsby",
    "gatsby-plugin",
    "gatsby-plugin-breakpoints",
    "breakpoints",
    "media query",
    "media queries",
    "hooks",
    "responsive"
  ],
  "main": "index.js",
  "author": "Jimmy Beldone <dev.jimmy.beldone@gmail.com>",
  "homepage": "https://github.com/JimmyBeldone/gatsby-plugin-breakpoints",
  "repository": {
    "type": "git",
    "url": "https://github.com/JimmyBeldone/gatsby-plugin-breakpoints.git"
  },
  "bugs": {
    "email": "dev.jimmy.beldone@gmail.com",
    "url": "https://github.com/JimmyBeldone/gatsby-plugin-breakpoints/issues"
  },
  "scripts": {
    "commit": "git-cz",
    "lint": "eslint src --fix",
    "pretty": "prettier --write 'src/**/*.js'",
    "test": "echo 'No test specified'",
    "prepare": "cross-env NODE_ENV=production yarn build && husky install",
    "build": "babel src --out-dir .",
    "semantic-release": "semantic-release"
  },
  "license": "MIT",
  "private": false,
  "devDependencies": {
    "@babel/cli": "7.19.3",
    "@babel/core": "7.19.3",
    "@babel/eslint-parser": "7.19.1",
    "@babel/preset-env": "7.19.4",
    "@babel/preset-react": "7.18.6",
    "@semantic-release/changelog": "6.0.1",
    "@semantic-release/git": "10.0.1",
    "babel-eslint": "10.1.0",
    "babel-preset-gatsby-package": "2.24.0",
    "commitizen": "4.2.5",
    "cross-env": "7.0.3",
    "cz-conventional-changelog": "3.3.0",
    "devmoji": "2.3.0",
    "eslint": "8.25.0",
    "eslint-config-airbnb-base": "15.0.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jest": "27.1.2",
    "eslint-plugin-jsx-a11y": "6.6.1",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-react": "7.31.10",
    "husky": "8.0.1",
    "lint-staged": "13.0.3",
    "prettier": "2.7.1",
    "prop-types": "15.8.1",
    "react": "18.2.0",
    "rimraf": "3.0.2",
    "semantic-release": "19.0.5"
  },
  "lint-staged": {
    "{src}/**/*.js": [
      "eslint --fix",
      "prettier --write"
    ]
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "dependencies": {
    "@babel/runtime": "^7.19.4"
  },
  "peerDependencies": {
    "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1 || ^17.0.0 || ^18.0.0"
  }
}
```

**Comment by hitfactory** [comment]
FYI the package.json in [https://www.npmjs.com/package/gatsby-plugin-breakpoints/v/1.3.9?activeTab=explore](https://www.npmjs.com/package/gatsby-plugin-breakpoints/v/1.3.9?activeTab=explore) is not the same as [https://github.com/JimmyBeldone/gatsby-plugin-breakpoints/blob/master/package.json](https://github.com/JimmyBeldone/gatsby-plugin-breakpoints/blob/master/package.json)

Seems like your recent change hasn't been published to npm correctly?

**Comment by therealtgd** [comment]
Same situation, please fix :D

**Comment by styfrombrest** [comment]
Faced with the same issue, @JimmyBeldone please take a look

**Comment by stephen-woods** [comment]
While we wait, you work around this issue by adding the following to your `package.json`

```json
"overrides": {
    "gatsby-plugin-breakpoints": {
      "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
    }
}
```

**Comment by joebentaylor1995** [comment]
> While we wait, you can work around this issue by adding the following to your `package.json`
> 
> ```json
> "overrides": {
>     "gatsby-plugin-breakpoints": {
>       "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
>     }
> }
> ```

This doesnt work for me

**Comment by joebentaylor1995** [comment]
Is there a specific place to put this in the package.json file or?

**Comment by stephen-woods** [comment]
I just put it right after my dependencies (same level):
```
{
  "dependencies": {
      "gatsby": "^5.5.0",
      <other dependencies here>
  },
  "overrides": {
    "gatsby-plugin-breakpoints": {
      "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
    }
  }
}
```

**Comment by joebentaylor1995** [comment]
Yeah, no look for meKind regards,JoeOn 16 Apr 2023, at 18:23, Steve Woods ***@***.***> wrote:﻿
I just put it right after my dependencies (same level):
{
  "dependencies": {
      "gatsby": "^5.5.0",
      <other dependencies here>
  },
  "overrides": {
    "gatsby-plugin-breakpoints": {
      "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
    }
  }
}

**Comment by joebentaylor1995** [comment]
Yeah, that unfortunately doesn't work for me

**Comment by Anaschoudhary** [comment]
Can anyone suggest another dependency?

**Comment by JimmyBeldone** [comment]
Hi guys ! 
Really sorry for the delay ! Just published a new version
