### ISSUE TITLE
 Error when using outside of a page or template

### ISSUE THREAD

**Issue by andres3dc** [JimmyBeldone/gatsby-plugin-breakpoints#33]
I'm adding gatsby-plugin-breakpoints in my header component and it returns me **useBreakpoint must be used within BreakpointProvider**

**Comment by JimmyBeldone** [comment]
Hey @andres3dc, 

Sorry for the late answer, I wasn't available this past 2 weeks.

Could you please share some code so I can help you with that ?

**Comment by bildungsroman** [comment]
I just hit something similar I think. I'm trying to use the plugin within a React Component within my Gatsby page, and getting the following error:

`Invalid hook call. Hooks can only be called inside of the body of a function component. `

**Comment by JimmyBeldone** [comment]
Hey @bildungsroman, 

Since I only use functional components I totally forgot about a solution for class components, sorry ^^"

I just added a HOC called `withBreakpoints` than you can use in class components and updated the documentation.

```javascript
/* yourClassComponent.js */

import { withBreakpoints } from 'gatsby-plugin-breakpoints';

import MobileOnlyComponent from './your/component/path'
// ...

class Test extends React.Component {
    render() {
        const { breakpoints } = this.props;
        {/* <MobileOnlyComponent /> will only be displayed if max-width <= 320px  */}
        return breakpoints.xs ? (
            <MobileOnlyComponent />
        ) : (
            <div>Content hidden only on mobile</div>
        );
    }
}

export default withBreakpoints(Test);
```

I close this issue but feel free to re open it if that doesn't fix your problem

**Comment by bildungsroman** [comment]
Awesome, thanks so much for the quick update!

**Comment by JimmyBeldone** [comment]
You're welcome ;)
