### ISSUE TITLE
BreakpointProvider is not exported.

### ISSUE THREAD

**Issue by michalisKout** [JimmyBeldone/gatsby-plugin-breakpoints#98]
Hello, I am using this library to render some responsive components in a gatsby project. It works fine in runtime.
On the other hand, I cannot test the components that are using the useBreakpoint. 

To test them, I need to wrap my testing component with the Breakpoint provider. The Breakpoint provider is not exported at the current release version.

for example in a **test.js** file:
```
import { BreakpointProvider } from ('gatsby-plugin-breakpoints');

it('should render with breakpoints', () => {
      const wrapper = render(<BreakpointProvider><NavBar isFixed menuData={defaultMenuData} /></BreakpointProvider> );
})
```

**Proposed solution** 

To export the Breakpoint provider from the **src/index.js** file:

```
import { useBreakpoint, BreakpointProvider } from './BreakpointProvider';
...
export { useBreakpoint, withBreakpoints, BreakpointProvider };
```

**Comment by JimmyBeldone** [comment]
Hey @michalisKout,

I just pushed a new version with `< BreakpointProvider />` exported and updated the doc.

You can now import it as so : 
```javascript
import { BreakpointProvider } from 'gatsby-plugin-breakpoints'
```

Let me now if it is ok for you.

**Comment by michalisKout** [comment]
Hello @JimmyBeldone ! 

I tried to export the BreakpointProvider and it works. Although, I cannot pass any dummy queries to it. Did I miss something ? 

example of my code:

**test.js file**
```
import { BreakpointProvider } from 'gatsby-plugin-breakpoints';
....


const mediaQueries = {
  xs: '(max-width: 320px)',
  sm: '(max-width: 480px)',
  md: '(max-width: 950px)',
  lg: '(max-width: 970px)',
  portrait: '(orientation: portrait)',
};

<BreakpointProvider queries={mediaQueries}>
       {children}
</BreakpointProvider>
```

I am getting the following error: 
`TypeError: Cannot convert undefined or null to object`
**path**: gatsby-plugin-breakpoints/BreakpointProvider.js:25:25
**line:25**:  const keys = Object.keys(queries);

Seems like it cannot accept any props. As result, it throws an exception.

**Comment by michalisKout** [comment]
Hello @JimmyBeldone, yeah it works fine! 
Thanks for the quick fix 😄 ! 

Do you want me to close this issue?

**Comment by JimmyBeldone** [comment]
Hey! @michalisKout 

No problem ^^

I'm closing the issue, feel free to re-open it if you have any troubles.
